### ISSUE TITLE
执行命令报错

### ISSUE THREAD

**Issue by chris6868** [sss128/emby-version-keeper#1]
# bash -c "$(curl https://raw.githubusercontent.com/sss128/emby-version-keeper/main/run.sh)" -s /docker/data/emby/config/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1050  100  1050    0     0   1553      0 --:--:-- --:--:-- --:--:--  1550
XIAOYA_ROOT: /docker/data/xiaoya
EMBY_SERVER: http://192.168.88.3:8096
TOKEN: 056da61fb3b440b5b8f5a2b1a162ee94
mode: 1
media:
Unable to find image 'sss128/emby-version-keeper:latest' locally
latest: Pulling from sss128/emby-version-keeper
a378f10b3218: Pull complete 
c11bdfacfd25: Pull complete 
83a1e03d76df: Pull complete 
77be58c2942e: Pull complete 
b085efd9f946: Pull complete 
f79c47414167: Pull complete 
3b3ae71c4481: Pull complete 
8a2505db1632: Pull complete 
509ea1af45ca: Pull complete 
Digest: sha256:87ba3e05c16ed8fa38ffbac9a74d10340fbbcd2f742028ca4963e9596f6f0a59
Status: Downloaded newer image for sss128/emby-version-keeper:latest
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/emby_version_handler.py", line 63, in <module>
    process(ProcessMode(int(sys.argv[1])), [])
  File "/app/emby_version_handler.py", line 43, in process
    for lib in get_emby_libraries():
               ^^^^^^^^^^^^^^^^^^^^
  File "/app/emby_api.py", line 19, in get_emby_libraries
    ).input_value(r.json())
                  ^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by chris6868** [comment]
emby4.8.0.62测试版

**Comment by sss128** [comment]
确认下emby里的apikey是不是和xiaoya目录的一致

**Comment by sss128** [comment]
确认下emby里的apikey是不是和xiaoya目录的一致

**Comment by chris6868** [comment]
> 确认下emby里的apikey是不是和xiaoya目录的一致

确认了的，是一样的

**Comment by chris6868** [comment]
![image](https://github.com/sss128/emby-version-keeper/assets/22971922/bb09faa3-aa36-4b3f-b504-fad816e797ca)还有这种找不到目录的问题，xiaoya目录是docker/data/xiaoya，但是每次他都找到的是xiaoya-tvbox的目录，既然要用xiaoya为什么不直接配置xiaoya的目录，而是emby的目录呢
